config/routes.rb
Filippas::Application.routes.draw do
    devise_for :users, :controllers => {:registrations => "registrations"} 
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    devise_scope :user do
      get '/login' => 'devise/sessions#new'
      get '/logout' => 'devise/sessions#destroy'
    end
    resources :token_authentications, :only => [:create, :destroy]
    resources :user, :controller => "user"
    resources :surveys
    
    namespace :user do
      root :to => "dashboard#userprofile"
    end
        match '/dashboard' => 'dashboard#userprofile', :as => 'user_root'
        match 'user/dashboard', :to => 'dashboard#userprofile'
        match '/userprofile', :to => 'dashboard#userprofile'
        match '/surveys/coupon', :to => 'surveys#coupon'
        match '/surveys/new', :to => 'surveys#new'
        match '/surveys/:id/coupon', :to => 'surveys#coupon'
        match '/contact', :to => 'pages#contact'
        match '/about',   :to => 'pages#about'
        match '/help',    :to => 'pages#help'
        match '/savetoexcel.php',    :to => 'pages#savetoexcel.php'
        match '/privacy', :to => 'pages#privacy'
        match '/hours', :to => 'pages#hours'
        match '/meetings', :to => 'pages#meetings'
        match '/restaurant',   :to => 'pages#restaurant'
        match '/banquet',    :to => 'pages#banquet'
        match '/catering', :to => 'pages#catering'
        match '/events',   :to => 'pages#events'
        match '/blog',    :to => 'pages#blog'
        match '/contact', :to => 'pages#contact'
        match '/menu', :to => 'pages#menu'
        root :to => 'pages#home'
    end
 

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController

  def show
       @user = User.find(params[:id])
       @title = @user.name
     end
  
end

app/helpers/layout_helper.rb
module LayoutHelper

  def stylesheet(*args)
      content_for(:head) { stylesheet_link_tag(*args.map(&:to_s)) }
    end

    def javascript(*args)
      args = args.map { |arg| arg == :defaults ? arg : arg.to_s }
      content_for(:head) { javascript_include_tag(*args) }
    end
end

app/views/layouts/_footer.html.erb
<div id="FooterContainer"> 

<div class="container_12"> 
<footer> 
	<div id="featuredTop"></div> 
	<div id="featuredContainer"> 
		<div class="grid_5 alpha"> 
			<form action="http://coastalcupboard.us2.list-manage.com/subscribe/post?u=e1e4741bd38ba69f3dc1ca535&amp;id=2d5a12e1af" method="post" id="signupForm" name="mc-embedded-subscribe-form" class="validate" target="_blank"> 
			<label for="EMAIL">Newsletter Sign Up</label> 
			<div id="signupField"> 
			<input type="text" value="Enter your email" name="EMAIL" class="required email cleardefault" id="mce-EMAIL" size="24" /> 
			</div> 
	<h1 class="signup"><a href="/emailsignup" title="Sign Up">Sign Up</a></h1>
			</form>
			<div class="highlights">
				<ul>
		<li><h6><%= link_to "Customer Survey", surveys_new_path %></h6></li> 
		<li><h6><a href="/specials" title="Sign Up">Latest Specials</a></h6></li>
		<li><h6><a href="/askthechef" title="Sign Up">Ask The Chef</a></h6></li> 
				</ul>
		</div> 
		</div>
		<div class="grid_2 alpha socialLinks"> 
			
			<h6>Stay Connected</h6> 
				<ul> 
<li class="facebook"><a href="http://www.facebook.com/filippaswinebarrel" title="Facebook">Facebook</a></li> 
<li class="twitter"><a href="http://twitter.com/filippas" title="Twitter">Twitter</a></li> 
<li class="email"><a href="/contact" title="Email">Email</a></li> 
				</ul>
				<ul>
				<li class="watermark"><a href="/contact" title="Contact">Contact</a></li>
				</ul> 
		</div>			
		<div class="grid_3 beta"> 
			<h6>Filippas Wine Barrel</h6> 
			<p> 45125 Mound Road<br /> Utica, MI 48317<br /> Map: <a href="http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=Filippa's+Wine+Barrel&aq=&sll=42.626144,-83.052371&sspn=0.010183,0.020385&ie=UTF8&hq=Filippa's+Wine+Barrel&hnear=&ll=42.627012,-83.054752&spn=0.081466,0.163078&z=13" title="Restaurant"><span>Directions to Filippas</span></a><br />
<b>Phone:</b> (586) 254.1311<br /> 
<b>Fax:</b> (586) 254.1311</p>
		</div>
		<div class="grid_2 omega"> 
			<h6>Store Hours</h6> 
			<p><b>Mon - Sat:</b> 11am - 10pm<br /> <b>Sunday:</b> 12pm - 9pm<br /><b> <a href="/hours" title="hours"><span>Full Hours & Holiday Schedule</span></a></p> 
		</div>

	</div> 
		<div id="featuredBtm"></div> 
</footer>
		<div class="grid_6"> 
				<div id="footerLinksLeft"> 
					<p>
						<a href="/restaurant/" title="Restaurant"><span>Restaurant</span></a> | 
						<a href="/banquet/" title="Banquet"><span>Banquet</span></a> | 
						<a href="/catering/" title="Catering"><span>Catering</span></a> | 
							<a href="/meetings/" title="Meetings"><span>Meetings</span></a>  | 
					<a href="/events/" title="Events"><span>Events</span></a>
					</p> 
					<p>All Rights Reserved. &copy; <%= Time.now.strftime("%Y") %>  Filippas Wine Barrel</p> 
				</div>
		</div> 
		<div class="grid_6"> 
				<div id="footerLinksRight"> 
					<p>
						<a href="/" title="Home">Home</a> | 
						<a href="/about/" title="About">About</a> | 
						<a href="/contact/" title="Contact">Contact</a> | 
						<a href="/blog/" title="Blog">Blog</a> | 
						<a href="/privacy/" title="Privacy">Privacy</a> | 
						<a href="/help/" title="Help">Help</a>  | 
						<% if user_signed_in? %>
						<%= link_to "Customer Survey", surveys_new_path %>       |    
						<%= link_to('Logout', destroy_user_session_path) %>        |   
						<%= link_to('Profile', userprofile_path) %> <% else %>   
						<%= link_to('Customer Survey', new_user_registration_path)  %>
						<% end %>
					</p> 
				</div>
		</div>

</div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
<div id="headerContainer"> 
<div class="logoback">
<div>
<div> 
<h1 class="logo"><a href="/" title="Home">Filippas Wine Barrel</a></h1> 
</div>
<div> 
		<ul id="topnav">
			<li class="first"><a href="/" title="Home"><span>Home</span></a></li> 
			<li><a href="/about/" title="About"><span>About</span></a></li> 
			<li><a href="/contact/" title="Contact"><span>Contact</span></a></li> 
			<li><a href="/blog/" title="Blog"><span>Blog</span></a></li>
				<li class="menulabel"><a href="/menu/" title="Menu"><span>Menu</span></a></li> 
			<li><% if user_signed_in? %>&nbsp; |&nbsp;<%= link_to('Logout', destroy_user_session_path) %>&nbsp;</li>
			<li><%= link_to('Profile', userprofile_path) %></li><% else %>
			<li><%= link_to('Login', new_user_session_path)  %>&nbsp; |&nbsp;</li>
			<li><%= link_to('Register', new_user_registration_path)  %><% end %></li>
			
		</ul>
		<ul id="topnav2">
		<li><% if user_signed_in? %>Welcome, <%= current_user.name %> <% end %></li>
		</ul>
	</div>
</div>

<div class="container_12">
<ul id="mainnav"> 
	<li class="first"><a href="/restaurant/" title="Restaurant"><span>Restaurant</span></a></li> 
	<li><a href="/banquet/" title="Banquet"><span>Banquet</span></a></li> 
	<li><a href="/catering/" title="Catering"><span>Catering</span></a></li> 
	<li><a href="/meetings/" title="Meetings"><span>Meetings</span></a></li>
	<li><a href="/events/" title="Events"><span>Events</span></a></li>
	<li><a href="/cookingclasses/" title="Cooking Classes"><span>Cooking Classes</span></a></li>
	<li class="winelabel"><a href="/wine/" title="Wine"><span>Wine</span></a></li>
</ul>

</div>
<h1 class="bottle"><a href="/wine" title="Wine">Michigan Wine Filippas Wine Barrel</a></h1> 
</div>

</div>
</div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'grid', :media => 'screen' %>
<%= stylesheet_link_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css', :media => 'screen' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'orbit', :media => 'screen' %>
 
<%= javascript_include_tag :defaults %>

<script>
			$(window).load(function() {
				$('#featured').orbit({
					"animation" : "horizontal-push"
				});
			});
		</script>
		
		
<%= yield(:head) %>

 <script>
	$(document).ready(function() {
	$("#tabs").tabs();
	});
</script>


  <script>

// When the document is ready, initialize the link so
// that when it is clicked, the printable area of the
// page will print.
$( function(){

// Hook up the print link.
$( "div#print_button" )
.attr( "href", "javascript:void( 0 )" )
.click(
function(){
// Print the DIV.
$( ".printable" ).print();

// Cancel click event.
return( false );
}
)
;

}
);

</script>
<script>

$(document).ready(function() {

$('#banner .homeNav li.panel1').fadeIn(
	function() {
		$('#banner .mouseover1').fadeIn(1000);
		$('#banner .homeNav li.panel1 .button a').addClass('fadeIn');
	},
	function() {
		$('#banner .mouseover1').fadeIn(1000);
		$('#banner .homeNav li.panel1 .button a').addClass('fadeIn');
	}
);
$('#banner .homeNav li.panel2').fadeIn(
	function() {
		$('#banner .mouseover2').fadeIn(1000);
		$('#banner .homeNav li.panel2 .button a').addClass('fadeIn');
	},
	function() {
		$('#banner .mouseover2').fadeIn(1000);
		$('#banner .homeNav li.panel2 .button a').addClass('fadeIn');
	}
);
$('#banner .homeNav li.panel3').fadeIn(
	function() {
		$('#banner .mouseover3').fadeIn(1000);
		$('#banner .homeNav li.panel3 .button a').addClass('fadeIn');
	},
	function() {
		$('#banner .mouseover3').fadeIn(1000);
		$('#banner .homeNav li.panel3 .button a').addClass('fadeIn');
	}
);
});
</script>

<script>
$(document).ready(function() {

$('#banner .homeNav li.panel1').hover(
	function() {
		$('#banner .homeNav li.panel1 .button a').addClass('hover');
	},
	function() {
		$('#banner .homeNav li.panel1 .button a').removeClass('hover');
	}
);
$('#banner .homeNav li.panel2').hover(
	function() {
		$('#banner .homeNav li.panel2 .button a').addClass('hover');
	},
	function() {
		$('#banner .homeNav li.panel2 .button a').removeClass('hover');
	}
);
$('#banner .homeNav li.panel3').hover(
	function() {
		$('#banner .homeNav li.panel3 .button a').addClass('hover');
	},
	function() {
		$('#banner .homeNav li.panel3 .button a').removeClass('hover');
	}
);
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
      <%= render 'layouts/header' %>
  <body>
	<div id="contentcontainer"> 
		<div class="wrap"> 
	<div class="container_12"> 
	        <%= yield %>
	</div>
	</div>
	</div>
  </body>
      <%= render 'layouts/footer' %>
	
</html>